version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_pass_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    build: .
    restart: always
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_pass_2024
      JWT_SECRET: packaging-equipment-jwt-secret-key-2024
      ADMIN_JWT_SECRET: packaging-equipment-admin-jwt-secret-2024
      APP_KEYS: app-key-1,app-key-2,app-key-3,app-key-4
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - uploads:/app/public/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    environment:
      STRAPI_URL: http://strapi:1337
    depends_on:
      - strapi
    volumes:
      - ./frontend/views:/app/views
      - ./frontend/public:/app/public

volumes:
  postgres_data:
  uploads:
